{% set name = "ffmpeg" %}
{% set version = "6.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n{{ version }}.tar.gz
  sha256: 7c1ebea95d815e49c1e60c7ee816410dec73a81b8ac002b276780d2f9048e598
  # This patch can be removed once the fix below is merged and uploaded,
  # the libxml2 2.13.1 buildout is done, and the libxml2 aggregate pinning
  # has been updated.
  # https://github.com/AnacondaRecipes/libxml2-feedstock/pull/16
  patches:
    - patches/0001-use-include-path-of-our-libxml2.patch # [win]
    - patches/pkgconfig_generate_windows_llvm.patch  # [win]
    - patches/0002-win64-ar-loging-removed.patch     # [win]

build:
  number: 4
  run_exports:
    # ABI is not broken between minor versions
    # https://ffmpeg.org/developer.html#Library-public-interfaces
    - {{ pin_subpackage('ffmpeg', max_pin='x') }}
  ignore_run_exports:
    - libcxx
    # these seems to be overdepending only on linux
    - libstdcxx-ng  # [linux]
    - aom           # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - autotools_clang_conda  # [win]
    - pkg-config
    - libtool  # [not win]
    - nasm
    - make  # [not win]
    - m2-patch  # [win]
  host:
    - aom         3.12.1
    - bzip2       {{ bzip2 }}
    - dav1d       1.2.1
    - freetype    {{ freetype }}
    - fontconfig  {{ fontconfig }}
    - harfbuzz    {{ harfbuzz }}
    - libiconv    1.16
    - zlib        {{ zlib }}
    - openh264    2.6.0           # [not win]
    - openjpeg    {{ openjpeg }}  # [not win]
    - librsvg     2.56.3          # [osx]
    - libtheora   1.2.0
    - libvorbis   1.3.7           # [not win]
    - libxml2     {{ libxml2 }}
    - tesseract   5.2.0           # [not win]
    - lame        3.100           # [not win]
    - libvpx      1.13.1          # [not win]
    - libopus     1.3             # [not win]
    - openssl     {{ openssl }}
    - xz          5.4.6
    - libglib     2.78.4          # [osx]
    - cairo       {{ cairo }}     # [osx]

  run:
    - aom                        # pinned through run_exports
    - bzip2                      # pinned through run_exports
    - dav1d                      # pinned through run_exports
    - freetype                   # pinned through run_exports
    - fontconfig                 # pinned through run_exports
    - harfbuzz                   # pinned through run_exports
    - libiconv                   # pinned through run_exports
    - zlib                       # pinned through run_exports
    - openh264                   # pinned through run_exports
    - openjpeg                   # pinned through run_exports
    - libtheora                  # pinned through run_exports
    - libvorbis                  # pinned through run_exports
    - libxml2                    # pinned through run_exports
    - tesseract                  # pinned through run_exports
    - lame                       # pinned through run_exports
    - libvpx                     # pinned through run_exports
    - libopus                    # pinned through run_exports
    - openssl                    # pinned through run_exports
    - xz                         # pinned through run_exports

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"     # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"   # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [not (win or s390x)]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"  # [not win]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avutil",
        "avcodec",
        "avdevice",
        "swresample",
        "avfilter",
        "avcodec",
        "avformat",
        "swscale"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $CONDA_PREFIX/lib/lib{{ each_ffmpeg_lib }}${SHLIB_EXT} # [not win]
    - if not exist %PREFIX%\Library\bin\{{ each_ffmpeg_lib }}*.dll exit 1  # [win]
    - if not exist %PREFIX%\Library\bin\{{ each_ffmpeg_lib }}.lib exit 1  # [win]
    {% endfor %}

about:
  home: https://www.ffmpeg.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING.LGPLv3
  license_family: LGPL
  summary: Cross-platform solution to record, convert and stream audio and video.
  description: |
    FFmpeg is a free and open-source software project consisting of a suite of libraries and programs for handling
    video, audio, and other multimedia files and streams. At its core is the command-line ffmpeg tool itself, designed
    for processing of video and audio files. It is widely used for format transcoding, basic editing (trimming and
    concatenation), video scaling, video post-production effects and standards compliance (SMPTE, ITU).
  dev_url: https://git.ffmpeg.org/gitweb/ffmpeg.git
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - carlodri
    - caspervdw
    - danielballan
    - jakirkham
    - jjhelmus
    - 183amir
    - mingwandroid
    - ocefpaf
    - patricksnape
    - sdvillal