{% set name = "ffmpeg" %}
{% set version = "7.0.1" %}
# win specific vars
{% set release_date = "2024-05-28" %}
{% set release_time = "12-46" %}
{% set release_commit = "g1800213575" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz  # [not win]
    sha256: e273eae00b4f833595654c1ee2b2349240e0332f9dbf3c4cadd39df9819ff052  # [not win]

  - url: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-{{ release_date }}-{{ release_time }}/{{ name }}-n{{ version }}-1-{{ release_commit }}-win64-gpl-shared-7.0.zip  # [win]
    sha256: 2c6a45e172f9322022b62afabff15bc17dfdd9f8e6de0a94e2dee90e01617c91  # [win]

  - url: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-{{ release_date }}-{{ release_time }}/{{ name }}-n{{ version }}-1-{{ release_commit }}-win64-gpl-7.0.zip  # [win]
    sha256: 051f7fe677e0bfa7d40e2f3b7ee2d2ca5c2cf7fc92f8bb828d0103dd560646fc  # [win]

build:
  number: 0
  # The windows build is repacking binaries rather than building from source
  run_exports:
  # seems to be minor version compatibility
  # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x.x') }}
  ignore_run_exports:
    - libcxx
    - gnutls
  missing_dso_whitelist:  # [osx]
    - /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox  # [osx]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - pkg-config  # [not win]
    - libtool  # [not win]
    - nasm  # [win or (osx and x86_64) or (linux and (not s390x))]
    - make  # [not win]
  host:
    - bzip2  # [not win]
    - freetype  # [not win]
    - gnutls  # [not win]
    - libiconv  # [not win and not linux]
    - x264  # [not (win or s390x)]
    - zlib  # [not win]
    - openh264  # [not win]
    - lame  # [not win]
    - gmp  # [not win]
    - libvpx  # [not (win or s390x)]
    - libopus # [not win]
    - openssl # [not win]
  run:
    - lame  # [not win]
    - xz    # [osx]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [not (win or s390x)]
    - ffmpeg -loglevel panic -codecs | grep "libx264"      # [not (win or s390x)]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "avcodec",
        "avformat",
        "swscale"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}

about:
  home: https://www.ffmpeg.org
  license: GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-3.0-or-later
  license_file:         # [not win]
    - COPYING.GPLv2     # [not win]
    - COPYING.GPLv3     # [not win]
    - COPYING.LGPLv2.1  # [not win]
    - COPYING.LGPLv3    # [not win]
    - LICENSE.md        # [not win]
  license_file: LICENSE.txt  # [win]
  license_family: OTHER
  summary: Cross-platform solution to record, convert and stream audio and video.
  dev_url: https://ffmpeg.org/developer.html
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - carlodri
    - caspervdw
    - danielballan
    - jakirkham
    - jjhelmus
    - 183amir
    - mingwandroid
    - ocefpaf
    - patricksnape
    - sdvillal
  skip-lints:
    - cbc_dep_in_run_missing_from_host