{% set version = "4.0" %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz  # [not win]
  sha256: dc4b1c622baa34fc68d763cd2818e419d1af90271e0506604905f25a46ea8273  # [not win]
  # This patch is required to fix https://trac.macports.org/ticket/55746
  # with Xcode < 7.0, where _Nullable attribues are not supported.
  # Can probably be removed once the compiler infrastructure is updated.
  patches:  # [osx]
    - patch-libavcodec-videotoolboxenc.c-drop-Nullable.patch  # [osx]

  fn: ffmpeg-{{ version }}-win32-shared.zip  # [win32]
  url: https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-{{ version }}-win32-shared.zip  # [win32]
  sha256: 530c92df0ca14c35901b4b681847d62da3c50a0cc9b7ced37b04968f6b5c243d  # [win32]

  fn: ffmpeg-{{ version }}-win64-shared.zip  # [win64]
  url: https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-{{ version }}-win64-shared.zip  # [win64]
  sha256: 8fe2d344463dbefc2db4239a4203a55ed0324faceaae57276a40c4fabda84c37  # [win64]

build:
  number: 0
  # The windows build is repacking binaries rather than building from source
  skip: True  # [win]
  run_exports:
    # seems to be minor version compatibility
    # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - libtool  # [not win]
    - yasm  # [not win]

  host:
    - bzip2  # [not win]
    - freetype  # [not win]
    - libiconv  # [osx]
    - zlib  # [not win]
    - freetype  # [not win]
    - libvpx  # [not win]
    - libopus  # [not win]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -codecs | grep "DEVI.S zlib"  # [unix]
    # macOS h264 support comes from the VideoToolbox Framework I guess?
    - ffmpeg -codecs | grep "DEV.LS h264"  # [osx]
    # It is unclear to me why this is supported on macOS. Hmm.
    - ffmpeg -protocols | grep "https"     # [osx]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "swresample",
        "avcodec",
        "avformat",
        "swscale",
        "avresample"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}

about:
  home: http://www.ffmpeg.org/
  license: GPL 3
  license_file: COPYING.GPLv3  # [unix]
  summary: Cross-platform solution to record, convert and stream audio and video.
  dev_url: https://ffmpeg.org/developer.html
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - carlodri
    - caspervdw
    - danielballan
    - jakirkham
    - jjhelmus
    - 183amir
    - mingwandroid
    - ocefpaf
    - patricksnape
    - sdvillal
