{% set name = "ffmpeg" %}
{% set version = "6.1.1" %}
# win specific vars
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set release_date = "2023-12-31" %}
{% set release_time = "12-55" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n{{ version }}.tar.gz
  sha256: 7c1ebea95d815e49c1e60c7ee816410dec73a81b8ac002b276780d2f9048e598

build:
  number: 0
  ignore_run_exports:
    - libcxx
    # these seems to be overdepending only on linux
    - libstdcxx-ng  # [linux]
    - aom           # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - autotools_clang_conda  # [win]
    - pkg-config
    - libtool  # [not win]
    - nasm  # [win or (osx and x86_64) or (linux and (not s390x))]
    - make  # [not win]
  host:
    - aom         3.6.0
    - bzip2       {{ bzip2 }}
    - dav1d       1.2.1
    - freetype    {{ freetype }}
    - fontconfig  {{ fontconfig }}
    - harfbuzz    {{ harfbuzz }}
    - libiconv    1.16
    - zlib        {{ zlib }}
    - openh264    2.1.1           # [not win]
    - openjpeg    {{ openjpeg }}  # [not win]
    - librsvg     2.54.4          # [osx]
    - libtheora   1.1.1
    - libvorbis   1.3.7           # [not win]
    - libxml2     {{ libxml2 }}
    - tesseract   5.2.0           # [not (win or s390x)]
    - lame        3.100           # [not win]
    - libvpx      1.13.1          # [not (win or s390x)]
    - libopus     1.3             # [not win]
    - openssl     {{ openssl }}
    - xz          5.4.6
    - libglib     2.78.4          # [osx]
    - cairo       1.16.0          # [osx]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"     # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"   # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [not (win or s390x)]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"  # [not win]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "avfilter",
        "avcodec",
        "avformat",
        "swscale"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $CONDA_PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $CONDA_PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    - if not exist %PREFIX%\Library\bin\{{ each_ffmpeg_lib }}*.dll exit 1  # [win]
    - if not exist %PREFIX%\Library\bin\{{ each_ffmpeg_lib }}.lib exit 1  # [win]
    {% endfor %}

about:
  home: https://www.ffmpeg.org
  license: GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-3.0-or-later
  license_file:
    - COPYING.LGPLv3
  license_family: OTHER
  summary: Cross-platform solution to record, convert and stream audio and video.
  description: |
    FFmpeg is a free and open-source software project consisting of a suite of libraries and programs for handling
    video, audio, and other multimedia files and streams. At its core is the command-line ffmpeg tool itself, designed
    for processing of video and audio files. It is widely used for format transcoding, basic editing (trimming and
    concatenation), video scaling, video post-production effects and standards compliance (SMPTE, ITU).
  dev_url: https://git.ffmpeg.org/gitweb/ffmpeg.git
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - carlodri
    - caspervdw
    - danielballan
    - jakirkham
    - jjhelmus
    - 183amir
    - mingwandroid
    - ocefpaf
    - patricksnape
    - sdvillal