{% set version = "4.2" %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  - url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz  # [not win]
    sha256: 9353228c2a397d1c62df7ca16033ec8a0cd2b12296de83a1c74948fe7395bb87  # [not win]

  - url: https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-{{ version }}-win64-shared.zip  # [win]
    sha256: 600ac804820fb12b989ff7f19f13f7866e1b79fbfe5e50f3bc43aee5fccdc392  # [win]

  - url: https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-{{ version }}-win64-dev.zip  # [win]
    sha256: 1beb19f168778fb631621c2eead96f9791fd6b63456ddc20ded5f2693cbdb5fc  # [win]

build:
  number: 0
  # The windows build is repacking binaries rather than building from source
  run_exports:
  # seems to be minor version compatibility
  # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox  # [osx]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - pkg-config  # [not win]
    - libtool  # [not win]
    - nasm  # [not win and not ppc64le and not aarch64]
    - make  # [not win]
  host:
    - bzip2  # [not win]
    - freetype  # [not win]
    # - gnutls  # [not win]
    - libiconv  # [osx]
    - x264  # [not win and not ppc64le and not aarch64]
    - zlib  # [not win]
    - openh264  # [not win and not ppc64le and not aarch64]
    - lame  # [not win]
    - gmp  # [unix]
    - libvpx  # [not win]
    - libopus # [not win]
    - openssl # [not win]
  run:
    - bzip2  # [not win]
    - freetype  # [not win]
    # - gnutls  # [not win]
    - openh264  # [not win and not ppc64le and not aarch64]
    - lame  # [not win]
    - gmp  # [unix]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -codecs
    - ffmpeg -loglevel panic -protocols | grep "https"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [linux64 or osx64]
    - ffmpeg -loglevel panic -codecs | grep "D.V.LS h264"  # [ppc64le]
    - ffmpeg -loglevel panic -codecs | grep "libx264"  # [linux64 or osx64]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"  # [linux64 or osx64]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "swresample",
        "avcodec",
        "avformat",
        "swscale",
        "avresample"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}

about:
  home: http://www.ffmpeg.org/
  license: GPL 3
  license_file: COPYING.GPLv3  # [unix]
  summary: Cross-platform solution to record, convert and stream audio and video.
  dev_url: https://ffmpeg.org/developer.html
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - carlodri
    - caspervdw
    - danielballan
    - jakirkham
    - jjhelmus
    - 183amir
    - mingwandroid
    - ocefpaf
    - patricksnape
    - sdvillal
