{% set version = "3.4" %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz
  sha256: 6ed03b00404a3923e3c2f560248a9c9ad79fbaaee26d723f74aae6b31fe2bae6
    
build:
  number: 0
  # The windows build is repacking binaries rather than building from source
  skip: True  # [win]
  run_exports:
    # seems to be minor version compatibility
    # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pkg-config  # [not win]
    - libtool     # [not win]
    - bzip2       # [not win]
    - zlib        # [not win]
    - libiconv    # [osx]
    - yasm
    - libvpx      # [not win]
    - libopus     # [not win]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -codecs | grep "DEVI.S zlib"  # [unix]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "avfilter",
        "swresample",
        "avcodec",
        "avformat",
        "swscale",
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}
    - conda inspect linkages -p $PREFIX ffmpeg  # [not win]
    - conda inspect objects -p $PREFIX ffmpeg  # [osx]

about:
  home: http://www.ffmpeg.org/
  license: LGPL 2.1
  license_family: LGPL
  license_file: COPYING.LGPLv2.1
  summary: Solution to record, convert and stream audio and video
  dev_url: https://ffmpeg.org/developer.html
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - danielballan
    - jakirkham
    - 183amir
    - caspervdw
